### ISSUE TITLE
Now .NET7

### ISSUE THREAD

**Issue by guillaume-chervet** [yostane/MangedDoom-Blazor#5]
@yostane :)

**Comment by yostane** [comment]
It doesn't work for now because of an interop method between .Net and JS that I use has been removed. However, there seems to be a better replacement now: https://devblogs.microsoft.com/dotnet/use-net-7-from-any-javascript-app-in-net-7/ and https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?view=aspnetcore-7.0.

It's time to check this out :)

**Comment by yostane** [comment]
Now uses .Net9 RC1 :)
